#include "BangoScripts_Editor.h"

#include "ClassViewerModule.h"
#include "Interfaces/IPluginManager.h"
#include "Kismet2/KismetEditorUtilities.h"
#include "Styling/SlateStyle.h"
#include "Styling/SlateStyleRegistry.h"

#include "BangoScripts/Components/BangoScriptComponent.h"
#include "BangoScripts/Core/BangoScript.h"
#include "BangoScripts/EditorTooling/BangoColors.h"
#include "BangoScripts/Editor/Customizations/Properties/BangoScriptContainerCustomization.h"
#include "BangoScripts/Core/BangoScriptContainer.h"

#include "Private/ComponentVisualizers/BangoScriptComponentVisualizer.h"
#include "Private/Menus/BangoEditorMenus.h"
#include "Private/BangoEditorStyle.h"
#include "Private/Commands/BangoEditorActions.h"
#include "Private/Customizations/BangoGraphPanelNodeFactory.h"
#include "Private/Utilities/BangoFolderUtility.h"

#define LOCTEXT_NAMESPACE "BangoScripts"

TSharedPtr<FSlateStyleSet> FBangoScripts_EditorModule::StyleSet = nullptr;
TSharedPtr<FBangoClassViewerFilter> FBangoScripts_EditorModule::BangoClassViewerFilter = nullptr;

// TODO clean this up
void FBangoScripts_EditorModule::StartupModule()
{
	AssetCategory = { "Bango", LOCTEXT("Bango", "Bango") };
	static const FName PropertyEditor("PropertyEditor");
	
	FPropertyEditorModule& PropertyEditorModule = FModuleManager::GetModuleChecked<FPropertyEditorModule>(PropertyEditor);

	
	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	
	const TSharedPtr<IPlugin> Plugin = IPluginManager::Get().FindPlugin(TEXT("BangoScripts"));
	check(Plugin.IsValid());
	
	const FString ResourcesDir = FPaths::ConvertRelativePathToFull(FPaths::Combine(Plugin->GetBaseDir(), TEXT("Resources")));
	
	StyleSet = MakeShareable(new FSlateStyleSet("BangoEditorStyleSet"));
	StyleSet->SetContentRoot(ResourcesDir);
	StyleSet->Set("ClassThumbnail.BangoEvent", new FSlateImageBrush(StyleSet->RootToContentDir(TEXT("ClassIcons/BangoEvent.png")), FVector2D(256, 256)));
	StyleSet->Set("ClassThumbnail.BangoAction", new FSlateImageBrush(StyleSet->RootToContentDir(TEXT("ClassIcons/BangoAction.png")), FVector2D(256, 256)));
	StyleSet->Set("ClassThumbnail.BangoTrigger", new FSlateImageBrush(StyleSet->RootToContentDir(TEXT("ClassIcons/BangoTrigger.png")), FVector2D(256, 256)));
	StyleSet->Set("Icon.Plunger", new FSlateVectorImageBrush(StyleSet->RootToContentDir(TEXT("NodeIcons/Icon_Plunger.svg")), FVector2D(16, 16)));
	StyleSet->Set("Icon.Plunger_Dim", new FSlateVectorImageBrush(StyleSet->RootToContentDir(TEXT("NodeIcons/Icon_Plunger.svg")), FVector2D(16, 16), Bango::Colors::White_Glass));
	
	FSlateStyleRegistry::RegisterSlateStyle(*StyleSet.Get());

	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

	PropertyEditorModule.NotifyCustomizationModuleChanged();
	
	FKismetEditorUtilities::RegisterAutoGeneratedDefaultEvent(this, UBangoScript::StaticClass(), "Start");
	
	IModuleInterface::StartupModule();
	
	/////////////////

	auto NodeFactory = MakeShareable(new FGraphPanelNodeFactory_Bango());
	FEdGraphUtilities::RegisterVisualNodeFactory(NodeFactory);
	
	/////////////////
	
	FBangoEditorStyle::Initialize();
	
	FBangoEditorCommands::Register();

	FBangoEditorMenus::BindCommands();
	
	FBangoEditorMenus::BuildMenus();
	
	//////////////////
	REGISTER_PROPERTY_CUSTOMIZATION(FBangoScriptContainer, FBangoScriptContainerCustomization);
	REGISTER_COMPONENT_VISUALIZER(UBangoScriptComponent, FBangoScriptComponentVisualizer);
	
	LateRegisterClassFilter();
	
	StartupModuleBase();
	
	FEditorDelegates::OnShutdownPostPackagesSaved.AddLambda([] ()
	{
		Bango::Editor::DeleteUnreferencedScripts();
		Bango::Editor::DeleteEmptyLevelScriptFolders();
	});
}

void FBangoScripts_EditorModule::ShutdownModule()
{
    ShutdownModuleBase();
}

void FBangoScripts_EditorModule::LateRegisterClassFilter()
{
	// TODO: project settings! IF PROJECT SETTINGS ONLY ENABLE CLASS FILTER FEATURE
	
	FEditorDelegates::OnEditorInitialized.AddLambda([this] (double TimeElapsed)
	{
		FTimerHandle DummyHandle;
		GEditor->GetTimerManager()->SetTimer(DummyHandle, FTimerDelegate::CreateLambda([this]()
		{
			FClassViewerModule& ClassViewerModule = FModuleManager::Get().LoadModuleChecked<FClassViewerModule>("ClassViewer");

			TSharedPtr<IClassViewerFilter> ExistingFilter = ClassViewerModule.GetGlobalClassViewerFilter();
			
			BangoClassViewerFilter = MakeShared<FBangoClassViewerFilter>(ExistingFilter);
			
			ClassViewerModule.RegisterGlobalClassViewerFilter(BangoClassViewerFilter.ToSharedRef());
			
		}), 1.0f, false);
	});
}

#undef LOCTEXT_NAMESPACE
    
IMPLEMENT_MODULE(FBangoScripts_EditorModule, BangoScripts_Editor) 

DEFINE_LOG_CATEGORY(BangoEditor);