#include "BangoEditor.h"

#include "ContentBrowserModule.h"
#include "LevelEditor.h"
#include "LevelEditorModesActions.h"
#include "SEditorViewport.h"
#include "AssetRegistry/AssetRegistryModule.h"
#include "Bango/Components/BangoActorIDComponent.h"
#include "Bango/Core/BangoScriptObject.h"
#include "BangoEditor/BangoColor.h"
#include "BangoEditor/BangoEditorStyle.h"
#include "BangoEditor/Commands/BangoEditorActions.h"
#include "BangoEditor/Customizations/BangoGraphPanelNodeFactory.h"
#include "BangoEditor/Customizations/Details/BangoEventComponentDetailsCustomization.h"
#include "BangoEditor/Customizations/Properties/ActionPropertyCustomization.h"
#include "BangoEditor/Customizations/Properties/BangoScriptHolderCustomization.h"
#include "BangoEditor/Customizations/Properties/TriggerPropertyCustomization.h"
#include "BangoEditor/Menus/BangoEditorMenus.h"
#include "Interfaces/IPluginManager.h"
#include "Kismet2/KismetEditorUtilities.h"
#include "Styling/SlateStyle.h"
#include "Styling/SlateStyleRegistry.h"
#include "Subsystems/EditorActorSubsystem.h"
#include "ViewportToolbar/UnrealEdViewportToolbar.h"
#include "Widgets/Input/STextEntryPopup.h"

#include "Bango/BangoScriptHolder.h"
#include "BangoEditor/Customizations/Properties/BangoScriptHolderCustomization.h"

#define LOCTEXT_NAMESPACE "BangoEditor"

TSharedPtr<FSlateStyleSet> FBangoEditorModule::StyleSet = nullptr;

void FBangoEditorModule::StartupModule()
{
	AssetCategory = { "Bango", LOCTEXT("Bango", "Bango") };
	static const FName PropertyEditor("PropertyEditor");
	
	FPropertyEditorModule& PropertyEditorModule = FModuleManager::GetModuleChecked<FPropertyEditorModule>(PropertyEditor);

	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

	{
		// TODO localization
		TSharedRef<FPropertySection> Section = PropertyEditorModule.FindOrCreateSection("Actor", "Bango", INVTEXT("Bango"));
		Section->AddCategory("Bango");
		TSharedRef<FPropertySection> Section2 = PropertyEditorModule.FindOrCreateSection("BangoEventComponent", "Bango", INVTEXT("Bango"));
		Section2->AddCategory("Bango");
	}
	
	const TSharedPtr<IPlugin> Plugin = IPluginManager::Get().FindPlugin(TEXT("Bango"));
	check(Plugin.IsValid());
	
	const FString ResourcesDir = FPaths::ConvertRelativePathToFull(FPaths::Combine(Plugin->GetBaseDir(), TEXT("Resources")));
	
	StyleSet = MakeShareable(new FSlateStyleSet("BangoEditorStyleSet"));
	StyleSet->SetContentRoot(ResourcesDir);
	StyleSet->Set("ClassThumbnail.BangoEvent", new FSlateImageBrush(StyleSet->RootToContentDir(TEXT("ClassIcons/BangoEvent.png")), FVector2D(256, 256)));
	StyleSet->Set("ClassThumbnail.BangoAction", new FSlateImageBrush(StyleSet->RootToContentDir(TEXT("ClassIcons/BangoAction.png")), FVector2D(256, 256)));
	StyleSet->Set("ClassThumbnail.BangoTrigger", new FSlateImageBrush(StyleSet->RootToContentDir(TEXT("ClassIcons/BangoTrigger.png")), FVector2D(256, 256)));
	StyleSet->Set("Icon.Plunger", new FSlateVectorImageBrush(StyleSet->RootToContentDir(TEXT("NodeIcons/Icon_Plunger.svg")), FVector2D(16, 16)));
	StyleSet->Set("Icon.Plunger_Dim", new FSlateVectorImageBrush(StyleSet->RootToContentDir(TEXT("NodeIcons/Icon_Plunger.svg")), FVector2D(16, 16), BangoColor::White_Glass));
	
	FSlateStyleRegistry::RegisterSlateStyle(*StyleSet.Get());

	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

	PropertyEditorModule.RegisterCustomPropertyTypeLayout("BangoAction", FOnGetPropertyTypeCustomizationInstance::CreateStatic(&FBangoActionPropertyCustomization::MakeInstance));
	PropertyEditorModule.RegisterCustomPropertyTypeLayout("BangoTrigger", FOnGetPropertyTypeCustomizationInstance::CreateStatic(&FBangoTriggerPropertyCustomization::MakeInstance));
	
	PropertyEditorModule.RegisterCustomClassLayout("BangoEventComponent", FOnGetDetailCustomizationInstance::CreateStatic(&FBangoEventComponentDetailsCustomization::MakeInstance));
	
	PropertyEditorModule.NotifyCustomizationModuleChanged();
	
	FKismetEditorUtilities::RegisterAutoGeneratedDefaultEvent(this, UBangoScriptInstance::StaticClass(), "Start");
	
	IModuleInterface::StartupModule();
	
	/////////////////

	auto NodeFactory = MakeShareable(new FGraphPanelNodeFactory_Bango());
	FEdGraphUtilities::RegisterVisualNodeFactory(NodeFactory);
	
	/////////////////
	
	FBangoEditorStyle::Initialize();
	
	FBangoEditorCommands::Register();

	FBangoEditorMenus::BindCommands();
	
	FBangoEditorMenus::BuildMenus();
	
	//////////////////
	REGISTER_PROPERTY_CUSTOMIZATION(FBangoScriptContainer, FBangoScriptContainerCustomization);
	
	FContentBrowserModule& CBModule =
			FModuleManager::LoadModuleChecked<FContentBrowserModule>("ContentBrowser");
		
	StartupModuleBase();
}

void FBangoEditorModule::ShutdownModule()
{
    ShutdownModuleBase();
}

#undef LOCTEXT_NAMESPACE
    
IMPLEMENT_MODULE(FBangoEditorModule, BangoEditor)

DEFINE_LOG_CATEGORY(BangoEditor);