#include "BangoEditor.h"

#include "BangoEditor/Private/BangoEditor/ComponentVisualizers/BangoScriptComponentVisualizer.h"
#include "ClassViewerModule.h"
#include "Bango/Components/BangoScriptComponent.h"
#include "Bango/Core/BangoScript.h"
#include "BangoEditorTooling/BangoColors.h"
#include "BangoEditor/BangoEditorStyle.h"
#include "BangoEditor/Commands/BangoEditorActions.h"
#include "BangoEditor/Customizations/BangoGraphPanelNodeFactory.h"
#include "BangoEditor/Customizations/Details/BangoEventComponentDetailsCustomization.h"
#include "BangoEditor/Customizations/Properties/ActionPropertyCustomization.h"
#include "BangoEditor/Customizations/Properties/BangoScriptContainerCustomization.h"
#include "BangoEditor/Customizations/Properties/TriggerPropertyCustomization.h"
#include "BangoEditor/Menus/BangoEditorMenus.h"
#include "Interfaces/IPluginManager.h"
#include "Kismet2/KismetEditorUtilities.h"
#include "Styling/SlateStyle.h"
#include "Styling/SlateStyleRegistry.h"

#include "Bango/Core/BangoScriptContainer.h"
#include "BangoEditor/Utilities/BangoFolderUtility.h"

#define LOCTEXT_NAMESPACE "BangoEditor"

TSharedPtr<FSlateStyleSet> FBangoEditorModule::StyleSet = nullptr;
TSharedPtr<FBangoClassViewerFilter> FBangoEditorModule::BangoClassViewerFilter = nullptr;

// TODO clean this up
void FBangoEditorModule::StartupModule()
{
	AssetCategory = { "Bango", LOCTEXT("Bango", "Bango") };
	static const FName PropertyEditor("PropertyEditor");
	
	FPropertyEditorModule& PropertyEditorModule = FModuleManager::GetModuleChecked<FPropertyEditorModule>(PropertyEditor);

	
	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

	{
		// TODO localization
		TSharedRef<FPropertySection> Section = PropertyEditorModule.FindOrCreateSection("Actor", "Bango", INVTEXT("Bango"));
		Section->AddCategory("Bango");
		TSharedRef<FPropertySection> Section2 = PropertyEditorModule.FindOrCreateSection("BangoEventComponent", "Bango", INVTEXT("Bango"));
		Section2->AddCategory("Bango");
	}
	
	const TSharedPtr<IPlugin> Plugin = IPluginManager::Get().FindPlugin(TEXT("Bango"));
	check(Plugin.IsValid());
	
	const FString ResourcesDir = FPaths::ConvertRelativePathToFull(FPaths::Combine(Plugin->GetBaseDir(), TEXT("Resources")));
	
	StyleSet = MakeShareable(new FSlateStyleSet("BangoEditorStyleSet"));
	StyleSet->SetContentRoot(ResourcesDir);
	StyleSet->Set("ClassThumbnail.BangoEvent", new FSlateImageBrush(StyleSet->RootToContentDir(TEXT("ClassIcons/BangoEvent.png")), FVector2D(256, 256)));
	StyleSet->Set("ClassThumbnail.BangoAction", new FSlateImageBrush(StyleSet->RootToContentDir(TEXT("ClassIcons/BangoAction.png")), FVector2D(256, 256)));
	StyleSet->Set("ClassThumbnail.BangoTrigger", new FSlateImageBrush(StyleSet->RootToContentDir(TEXT("ClassIcons/BangoTrigger.png")), FVector2D(256, 256)));
	StyleSet->Set("Icon.Plunger", new FSlateVectorImageBrush(StyleSet->RootToContentDir(TEXT("NodeIcons/Icon_Plunger.svg")), FVector2D(16, 16)));
	StyleSet->Set("Icon.Plunger_Dim", new FSlateVectorImageBrush(StyleSet->RootToContentDir(TEXT("NodeIcons/Icon_Plunger.svg")), FVector2D(16, 16), Bango::Colors::White_Glass));
	
	FSlateStyleRegistry::RegisterSlateStyle(*StyleSet.Get());

	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

	PropertyEditorModule.RegisterCustomPropertyTypeLayout("BangoAction", FOnGetPropertyTypeCustomizationInstance::CreateStatic(&FBangoActionPropertyCustomization::MakeInstance));
	PropertyEditorModule.RegisterCustomPropertyTypeLayout("BangoTrigger", FOnGetPropertyTypeCustomizationInstance::CreateStatic(&FBangoTriggerPropertyCustomization::MakeInstance));
	
	PropertyEditorModule.RegisterCustomClassLayout("BangoEventComponent", FOnGetDetailCustomizationInstance::CreateStatic(&FBangoEventComponentDetailsCustomization::MakeInstance));
	
	PropertyEditorModule.NotifyCustomizationModuleChanged();
	
	FKismetEditorUtilities::RegisterAutoGeneratedDefaultEvent(this, UBangoScript::StaticClass(), "Start");
	
	IModuleInterface::StartupModule();
	
	/////////////////

	auto NodeFactory = MakeShareable(new FGraphPanelNodeFactory_Bango());
	FEdGraphUtilities::RegisterVisualNodeFactory(NodeFactory);
	
	/////////////////
	
	FBangoEditorStyle::Initialize();
	
	FBangoEditorCommands::Register();

	FBangoEditorMenus::BindCommands();
	
	FBangoEditorMenus::BuildMenus();
	
	//////////////////
	REGISTER_PROPERTY_CUSTOMIZATION(FBangoScriptContainer, FBangoScriptContainerCustomization);
	REGISTER_COMPONENT_VISUALIZER(UBangoScriptComponent, FBangoScriptComponentVisualizer);
	
	LateRegisterClassFilter();
	
	StartupModuleBase();
	
	FEditorDelegates::OnShutdownPostPackagesSaved.AddLambda([] ()
	{
		Bango::Editor::DeleteUnreferencedScripts();
		Bango::Editor::DeleteEmptyScriptFolders();
	});
}

void FBangoEditorModule::ShutdownModule()
{
    ShutdownModuleBase();
}

void FBangoEditorModule::LateRegisterClassFilter()
{
	// TODO: project settings! IF PROJECT SETTINGS ONLY ENABLE CLASS FILTER FEATURE
	
	FEditorDelegates::OnEditorInitialized.AddLambda([this] (double TimeElapsed)
	{
		FTimerHandle DummyHandle;
		GEditor->GetTimerManager()->SetTimer(DummyHandle, FTimerDelegate::CreateLambda([this]()
		{
			FClassViewerModule& ClassViewerModule = FModuleManager::Get().LoadModuleChecked<FClassViewerModule>("ClassViewer");

			TSharedPtr<IClassViewerFilter> ExistingFilter = ClassViewerModule.GetGlobalClassViewerFilter();
			
			BangoClassViewerFilter = MakeShared<FBangoClassViewerFilter>(ExistingFilter);
			
			ClassViewerModule.RegisterGlobalClassViewerFilter(BangoClassViewerFilter.ToSharedRef());
			
		}), 1.0f, false);
	});
}

#undef LOCTEXT_NAMESPACE
    
IMPLEMENT_MODULE(FBangoEditorModule, BangoEditor)

DEFINE_LOG_CATEGORY(BangoEditor);